# Form implementation generated from reading ui file 'D:\TMĐT HK6\4.Machine learning\MLBA\ML_exercise\qtdesigner\ui\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 439)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 40, 621, 331))
        self.groupBox.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(50, 40, 241, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(50, 80, 191, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(50, 120, 221, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(50, 160, 251, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(50, 200, 251, 21))
        self.label_5.setObjectName("label_5")
        self.pushButtonPredict = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonPredict.setGeometry(QtCore.QRect(50, 240, 111, 31))
        self.pushButtonPredict.setObjectName("pushButtonPredict")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(50, 290, 251, 21))
        self.label_6.setObjectName("label_6")
        self.lineEditIncome = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditIncome.setGeometry(QtCore.QRect(310, 40, 281, 20))
        self.lineEditIncome.setObjectName("lineEditIncome")
        self.lineEditAge = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditAge.setGeometry(QtCore.QRect(310, 80, 281, 20))
        self.lineEditAge.setObjectName("lineEditAge")
        self.lineEditRooms = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditRooms.setGeometry(QtCore.QRect(310, 120, 281, 20))
        self.lineEditRooms.setObjectName("lineEditRooms")
        self.lineEditBedRooms = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditBedRooms.setGeometry(QtCore.QRect(310, 160, 281, 20))
        self.lineEditBedRooms.setObjectName("lineEditBedRooms")
        self.lineEditPopulation = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditPopulation.setGeometry(QtCore.QRect(310, 200, 281, 20))
        self.lineEditPopulation.setObjectName("lineEditPopulation")
        self.lineEditPredict = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditPredict.setGeometry(QtCore.QRect(310, 290, 281, 20))
        self.lineEditPredict.setObjectName("lineEditPredict")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Housing Price Prediction:"))
        self.label.setText(_translate("MainWindow", "Avg. Area Income:"))
        self.label_2.setText(_translate("MainWindow", "Avg. Area House Age:"))
        self.label_3.setText(_translate("MainWindow", "Avg. Area Number of Rooms:"))
        self.label_4.setText(_translate("MainWindow", "Avg. Area Number of Bedrooms:"))
        self.label_5.setText(_translate("MainWindow", "Area Population:"))
        self.pushButtonPredict.setText(_translate("MainWindow", "Prediction"))
        self.label_6.setText(_translate("MainWindow", "House Pricing Prediction:"))
